# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.10.2-stretch
deployment: production
options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - docker
        script: # Modify the commands below to build your repository.
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t jayflux/fancast-api:latest .
          - docker push jayflux/fancast-api:latest
