version: "3.5"
services:
  db:
    build:
      context: .

    container_name: fancast-api
    image: jayflux/fancast-api
    hostname: fancast-api
    networks:
      - proxynet
    volumes:
      - .:/usr/local/src/bitbucket.org/jayflux/mypodcasts_injest
    ports:
      - "5432:5432"
      - "8060:8060"
    env_file: envs
    tty: true

networks:
  proxynet:
    name: custom_network
